# Generated by Django 2.2.6 on 2019-10-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker_b',
            name='Answer',
            field=models.CharField(max_length=5),
        ),
    ]
