# Generated by Django 2.2.5 on 2019-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Working_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('TestCategory', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=2)),
            ],
        ),
    ]
