# Generated by Django 2.2.5 on 2019-10-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania_V2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_test',
            name='Level',
            field=models.CharField(max_length=50),
        ),
    ]
